<template>
    <div class="load__conatiner">
        <figure>
            <!-- <?xml version="1.0" encoding="utf-8"?> -->
            <svg
                class="load__svg"
                xmlns="http://www.w3.org/2000/svg"
                xmlns:xlink="http://www.w3.org/1999/xlink"
                style="margin: auto; background: none; display: block; shape-rendering: auto;"
                width="200px"
                height="200px"
                viewBox="0 0 100 100"
                preserveAspectRatio="xMidYMid"
            >
                <circle
                    cx="50"
                    cy="50"
                    r="32"
                    stroke-width="8"
                    stroke="#023047"
                    stroke-dasharray="50.26548245743669 50.26548245743669"
                    fill="none"
                    stroke-linecap="round"
                >
                    <animateTransform
                        attributeName="transform"
                        type="rotate"
                        dur="1s"
                        repeatCount="indefinite"
                        keyTimes="0;1"
                        values="0 50 50;360 50 50"
                    ></animateTransform>
                </circle>
                <circle
                    cx="50"
                    cy="50"
                    r="23"
                    stroke-width="8"
                    stroke="#f7931e"
                    stroke-dasharray="36.12831551628262 36.12831551628262"
                    stroke-dashoffset="36.12831551628262"
                    fill="none"
                    stroke-linecap="round"
                >
                    <animateTransform
                        attributeName="transform"
                        type="rotate"
                        dur="1s"
                        repeatCount="indefinite"
                        keyTimes="0;1"
                        values="0 50 50;-360 50 50"
                    ></animateTransform>
                </circle>
                <!-- [ldio] generated by https://loading.io/ -->
            </svg>
        </figure>
    </div>
</template>

<script>
export default {};
</script>

<style scoped lang="scss">
.load__conatiner {
    display: flex;
    flex-direction: row;
    justify-content: center;
    align-items: center;
    height: 30vh;
    width: 100%;
}

@media only screen and (max-width: 2000px) {
    .load__svg {
        width: 130px;
        height: 130px;
    }
}

@media only screen and (max-width: 600px) {
    .load__conatiner {
        height: auto;
    }
}

@media only screen and (max-width: 560px) {
    .load__svg {
        width: 100px;
        height: 100px;
    }
}

@media only screen and (max-width: 370px) {
    .load__svg {
        width: 70px;
        height: 70px;
    }
}
</style>
