<template>
    <section>
        <div class="modal__block">
            <div>
                <div class="success__icon">
                    <svg
                        xml:space="preserve"
                        viewBox="0 0 100 100"
                        y="0"
                        x="0"
                        xmlns="http://www.w3.org/2000/svg"
                        id="圖層_1"
                        version="1.1"
                        width="200px"
                        height="200px"
                        xmlns:xlink="http://www.w3.org/1999/xlink"
                        style="width:100%;height:100%;background-size:initial;background-repeat-y:initial;background-repeat-x:initial;background-position-y:initial;background-position-x:initial;background-origin:initial;background-color:initial;background-clip:initial;background-attachment:initial;animation-play-state:paused"
                    >
                        <g
                            class="ldl-scale"
                            style="transform-origin:50% 50%;transform:rotate(0deg) scale(0.8, 0.8);animation-play-state:paused"
                        >
                            <path
                                stroke-miterlimit="10"
                                stroke-width="9"
                                stroke="#e15b64"
                                fill="#fff"
                                d="M41.6 18.9L11.3 71.4c-3.7 6.5.9 14.6 8.4 14.6h60.6c7.5 0 12.1-8.1 8.4-14.6L58.4 18.9c-3.7-6.4-13.1-6.4-16.8 0z"
                                style="stroke:rgb(225, 91, 100);fill:rgb(255, 255, 255);animation-play-state:paused"
                            ></path>
                            <circle
                                fill="#333"
                                r="5.4"
                                cy="69.4"
                                cx="50"
                                style="fill:rgb(2, 48, 71);animation-play-state:paused"
                            ></circle>
                            <path
                                fill="#333"
                                d="M55.4 43.8c0 6-1.6 11.3-3.1 14.9-.8 2.1-3.8 2.1-4.7 0-1.5-3.6-3.1-9-3.1-14.9 0-8.9 2.4-11.9 5.4-11.9s5.5 3 5.5 11.9z"
                                style="fill:rgb(2, 48, 71);animation-play-state:paused"
                            ></path>
                            <metadata
                                xmlns:d="https://loading.io/stock/"
                                style="animation-play-state:paused"
                            >
                                <d:name style="animation-play-state:paused"
                                    >caution</d:name
                                >
                                <d:tags style="animation-play-state:paused"
                                    >hint,note,warning,danger,reminder,sign,exclamation,caution,transportation</d:tags
                                >
                                <d:license style="animation-play-state:paused"
                                    >by</d:license
                                >
                                <d:slug style="animation-play-state:paused"
                                    >1t5sok</d:slug
                                >
                            </metadata>
                        </g>
                        <!-- generated by https://loading.io/ -->
                    </svg>
                </div>
                <p class="text">{{ postTitle }}</p>
            </div>
        </div>
    </section>
</template>

<script>
export default {
    props: ["postTitle"],
    data() {
        return {
            sendReqModal: true
        };
    }
};
</script>

<style scoped lang="scss">
.modal__block {
    position: fixed;
    top: 5vh;
    left: 0;

    width: 100%;
    z-index: 9999;
    display: flex;
    justify-content: center;
    align-items: center;
    overflow: hidden;

    animation: modal-scale 0.7s linear forwards,
        modal-opacity 2s linear forwards;
    div {
        max-width: 80%;
        color: #155724;
        background-color: #fcf6f6;
        border-color: #c3e6cb;
        border-radius: 4px;
        padding: 3px 8px;

        display: flex;

        justify-content: center;
        align-items: center;
        overflow: hidden;
    }

    .text {
        margin: 0 0 0 4px;
        display: block;
    }
}

@keyframes modal-scale {
    0% {
        transform: scale(0.1);
    }

    50% {
        transform: scale(1);
    }

    100% {
        transform: scale(1);
    }
}

@keyframes modal-opacity {
    0% {
        opacity: 0;
    }

    33% {
        opacity: 1;
    }

    88% {
        opacity: 1;
    }

    100% {
        opacity: 0;
    }
}

.success__icon {
    width: 60px;
    animation: scaleIcon 2s linear forwards;
}

@keyframes scaleIcon {
    0% {
        transform: scale(1);
    }
    25% {
        transform: scale(0.88);
    }
    50% {
        transform: scale(1);
    }
    75% {
        transform: scale(1.1);
    }
    100% {
        transform: scale(1.1);
    }
}

.exl path {
    fill: transparent;
    stroke-width: 2px;
    stroke: rgb(247, 147, 31);
    // animation: animate-success 1.5s linear forwards;
}

// @keyframes animate-success {
//     0% {
//         stroke-dashoffset: 0;
//     }

//     40% {
//         stroke-dashoffset: 150;
//     }

//     80% {
//         stroke-dashoffset: 300;
//     }

//     100% {
//         stroke-dashoffset: 300;
//         fill: rgb(247, 147, 31);
//     }
// }

@media only screen and (max-width: 400px) {
    .modal__block {
        div {
            max-width: 70%;
        }

        .text {
            font-size: 12px;
        }
    }

    .success__icon {
        width: 80px;
    }
}
</style>
