<template>
    <section>
        <div class="modal__block">
            <div>
                <div class="success__icon">
                    <svg
                        xml:space="preserve"
                        viewBox="0 0 100 100"
                        y="0"
                        x="0"
                        xmlns="http://www.w3.org/2000/svg"
                        id="圖層_1"
                        version="1.1"
                        width="200px"
                        height="200px"
                        xmlns:xlink="http://www.w3.org/1999/xlink"
                        style="width:100%;height:100%;background-size:initial;background-repeat-y:initial;background-repeat-x:initial;background-position-y:initial;background-position-x:initial;background-origin:initial;background-color:initial;background-clip:initial;background-attachment:initial;animation-play-state:play"
                    >
                        <g
                            class="ldl-scale"
                            style="transform-origin:50% 50%;transform:rotate(0deg) scale(0.8, 0.8);animation-play-state:play"
                        >
                            <circle
                                stroke-miterlimit="10"
                                stroke-width="
						5"
                                stroke="#333"
                                fill="none"
                                r="40"
                                cy="50"
                                cx="50"
                                style="stroke:rgb(2, 48, 71);animation-play-state:play"
                            ></circle>
                            <g style="animation-play-state:play" class="exl">
                                <path
                                    d="M43.7 69.4L25 47.7l3.9-3.9 14.8 12.6 28.6-25.8 2.7 2.7z"
                                    fill="#abbd81"
                                    style="fill:rgb(247, 147, 31);animation-play-state:play"
                                ></path>
                            </g>
                            <metadata
                                xmlns:d="https://loading.io/stock/"
                                style="animation-play-state:play"
                            >
                                <d:name style="animation-play-state:play"
                                    >ok</d:name
                                >
                                <d:tags style="animation-play-state:play"
                                    >ok,confirm,ready,positive,check,right,correct,affirmative,success</d:tags
                                >
                                <d:license style="animation-play-state:play"
                                    >by</d:license
                                >
                                <d:slug style="animation-play-state:play"
                                    >47ibm8</d:slug
                                >
                            </metadata>
                        </g>
                        <!-- generated by https://loading.io/ -->
                    </svg>
                </div>
                <p class="text">{{ postTitle }}</p>
            </div>
        </div>
    </section>
</template>

<script>
export default {
    props: ["postTitle"],
    data() {
        return {
            sendReqModal: true
        };
    }
};
</script>

<style scoped lang="scss">
.modal__block {
    position: fixed;
    top: 0;
    left: 0;

    width: 100%;
    z-index: 9999;
    display: flex;
    justify-content: center;
    align-items: center;
    overflow: hidden;

    animation: modal-top 0.8s linear forwards,
        modal-opacity 1.5s linear forwards;
    div {
        max-width: 80%;
        color: #155724;
        background-color: #fcf6f6;
        border-color: #c3e6cb;
        border-radius: 4px;
        padding: 3px 8px;

        display: flex;

        justify-content: center;
        align-items: center;
        overflow: hidden;
    }

    .text {
        margin: 0 0 0 4px;
        display: block;
    }
}

@keyframes modal-top {
    0% {
    }

    50% {
        top: 5vh;
    }

    100% {
        top: 5vh;
    }
}

@keyframes modal-opacity {
    0% {
        opacity: 0;
    }

    33% {
        opacity: 1;
    }

    88% {
        opacity: 1;
    }

    100% {
        opacity: 0;
    }
}

.success__icon {
    width: 60px;
    animation: scaleIcon 2s linear forwards;
}

@keyframes scaleIcon {
    0% {
        transform: scale(1);
    }
    25% {
        transform: scale(0.88);
    }
    50% {
        transform: scale(1);
    }
    75% {
        transform: scale(1.1);
    }
    100% {
        transform: scale(1.1);
    }
}

.exl path {
    fill: transparent;
    stroke-width: 2px;
    stroke: rgb(247, 147, 31);
    // animation: animate-success 1.5s linear forwards;
}

// @keyframes animate-success {
//     0% {
//         stroke-dashoffset: 0;
//     }

//     40% {
//         stroke-dashoffset: 150;
//     }

//     80% {
//         stroke-dashoffset: 300;
//     }

//     100% {
//         stroke-dashoffset: 300;
//         fill: rgb(247, 147, 31);
//     }
// }

@media only screen and (max-width: 400px) {
    .modal__block {
        div {
            max-width: 70%;
        }

        .text {
            font-size: 12px;
        }
    }

    .success__icon {
        width: 80px;
    }
}
</style>
